Update docs (text fixes, sample regions json)
heartexlabs/label-studio pull request #1332
Opened 2021-08-19 15:42 UTC by hlomzik

Generated automatically, all the fixes should go to https://github.com/heartexlabs/label-studio-frontend/pull/236

2021-08-19 21:22 UTC, smoreface commented on docs/source/tags/ellipselabels.md
> +### Example JSON```js
typo here --> 
needs to be

### Example JSON

```json

not 
### Example JSON```js

2021-08-19 21:23 UTC, smoreface commented on docs/source/tags/hypertext.md
> +### Example JSON```js
must be a typo in the conversion script

2021-08-19 21:38 UTC, smoreface requested changes
Need to fix the script to properly encode example JSON and also update based on latest changes in [#236](https://github.com/heartexlabs/label-studio-frontend/pull/236/files)

2021-08-20 16:23 UTC, hlomzik commented
> Need to fix the script to properly encode example JSON

I used `js` because it looks a bit better than `json` formatting. But looks good anyway and semantic is better, so changed it, thanks. And fixed script

2021-08-20 17:36 UTC, smoreface approved these changes
looks good, thanks for the fixes!

2021-08-22 18:23 UTC, merged