Added Validation check for export storage
heartexlabs/label-studio pull request #2088
Opened 2022-03-03 15:05 UTC by HeartexDL

2022-03-03 22:07 UTC, makseq requested changes

2022-03-04 17:35 UTC, makseq requested changes

2022-03-04 17:35 UTC, makseq commented on label_studio/io_storages/redis/serializers.py
> +        except:
please don't use so broad exceptions, better to write 
except Exception as exc:

2022-03-04 19:33 UTC, makseq requested changes

2022-03-07 18:51 UTC, HeartexDL commented on label_studio/io_storages/s3/serializers.py
> +        except:
@makseq So do we need to remove this exception ?

2022-03-08 16:55 UTC, makseq submitted a review, later dismissed

2022-03-15 09:40 UTC, KonstantinKorotaev approved these changes

2024-04-24 17:43 UTC, closed without merging