docs: DEVE-2634 Remove Step 2 in "Configure access to your S3 bucket"
heartexlabs/label-studio pull request #2526
Opened 2022-06-15 22:36 UTC by anithamuthu2022

2022-06-16 08:01 UTC, antopolskiy requested changes
I'd add a note that Session Token is only required in case of temporary security credentials, so that there is no confusion.

otherwise lgtm

2022-06-17 16:41 UTC, makseq approved these changes

2022-06-17 16:41 UTC, merged

2022-06-17 16:44 UTC, anithamuthu2022 commented
> I'd add a note that Session Token is only required in case of temporary security credentials, so that there is no confusion.
> 
> otherwise lgtm

[s.antopolsky@gmail.com](mailto:s.antopolsky@gmail.com) could you test and confirm the change.

2022-06-18 12:39 UTC, antopolskiy commented
lgtm