docs: DEV-3288: Add doc how to load data from LS from ML backend
heartexlabs/label-studio pull request #2909
Opened 2022-09-08 10:12 UTC by KonstantinKorotaev

2022-09-09 17:36 UTC, makseq requested changes

2022-09-12 07:59 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +### Accessing data from Label Studio box
Changed to instance

2022-09-12 12:44 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +There are several ways of storing tasks data in Label Studio:
Fixed

2022-09-12 14:58 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +You can use label_studio_tools.core.utils.io.get_local_path to get task data - it will transform path or URL from task data to local path.
Fixed

2022-09-12 14:59 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +### Accessing data outside of Label Studio box
Fixed

2022-09-12 14:59 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +Label Studio stores local files in Project level structure. Each project has it's own folder for files.
Fixed

2022-09-12 15:00 UTC, KonstantinKorotaev commented on docs/source/guide/export.md
> +## Access data outside of Label Studio
Fixed

2022-09-13 01:17 UTC, makseq approved these changes

2022-09-19 17:00 UTC, makseq approved these changes

2022-09-19 17:03 UTC, merged