docs: Add order_enterprise: <number>
heartexlabs/label-studio pull request #3299
Opened 2022-11-23 19:40 UTC by anithamuthu2022

[DOC-92]

2022-11-23 19:43 UTC, anithamuthu2022 commented
https://user-images.githubusercontent.com/107003313/203633086-82219f3d-3ba8-49f3-8240-1ddd31ef7c63.mov

@huguestennier I've added `order:enterprise: <number> in the pages so that I would be able to see the following hierarchy of ordering in the left nav on the ENT website only. 

Unfortunately, it is not showing up as expected in the local build. What is the possible change here to make sure the left nav in the ENT website has the following order of pages?

```GET STARTED
CONFIGURATION
IMPORT AND EXPORT
LABELING
QUALITY CONTROL
MACHINE LEARNING
INTEGRATION AND DEVELOPMENT
SECURITY AND PRIVACY
BILLING AND USAGE
INSTALL
ADVANCED DEVELOPMENT```

2022-11-23 20:18 UTC, huguestennier commented
@anithamuthu2022 before you create a new branch, make sure you the original branch is up to date. It wasn’t working because it was missing the code. I made a commit to make sure you have the latest code, should work now.

2022-11-23 20:37 UTC, anithamuthu2022 commented
@huguestennier can you review/approve this PR so I can see the new left nav on the ENT website?

I still don't see it in. my local build.

2022-11-24 00:00 UTC, makseq commented
opensource:
![image](https://user-images.githubusercontent.com/501780/203665904-fb58cde1-e8aa-4438-8c81-59c67e347282.png)

2022-11-24 00:04 UTC, makseq commented
enterprise order is broken now: 
![image](https://user-images.githubusercontent.com/501780/203666217-0f849c01-d9df-4758-9be5-0bdefcb0617e.png)

2022-11-24 00:04 UTC, makseq requested changes
see my 2 previous comments

2022-11-24 00:16 UTC, anithamuthu2022 commented
ENT order is addressed on the PR.
GET STARTED
CONFIGURATION
IMPORT AND EXPORT
LABELING
QUALITY CONTROL
MACHINE LEARNING
INTEGRATION AND DEVELOPMENT
SECURITY AND PRIVACY
BILLING AND USAGE
INSTALL

2022-11-24 00:16 UTC, anithamuthu2022 commented
OSS order on the PR=> expected order is:
Get Started
Install
Configuration
Import and Export
Labeling 
Machine Learning 
Integration and Development

2022-11-28 19:03 UTC, anithamuthu2022 commented
@huguestennier I've edited the `home.ejs` file to meet the following requirements for the landing page, but I see the following errors: 

1. Both OSS and ENT landing pages have all the tile cards for OSS and ENT on the same page. This is not the expected behavior, but it should display only the [order of pages explained in Slack](https://heartex.slack.com/archives/C03UN6A0CQN/p1669655427316309?thread_ts=1669237012.108109&cid=C03UN6A0CQN) and also should include the two main tiles on the landing page. 
<img width="1294" alt="Screen Shot 2022-11-28 at 10 52 48 AM" src="https://user-images.githubusercontent.com/107003313/204357608-eadf4b81-e929-477d-bec8-d821fe1b1da8.png">

2. The `Getting Started` tile and `Overview` tile are missing from OSS and ENT's landing page when you run the local build. 

<img width="450" alt="Screen Shot 2022-11-28 at 10 55 12 AM" src="https://user-images.githubusercontent.com/107003313/204358004-1f146d0e-bc85-4278-815e-3df4db30b89e.png">
<img width="669" alt="Screen Shot 2022-11-28 at 10 55 05 AM" src="https://user-images.githubusercontent.com/107003313/204358007-48c7cd33-91bb-4e06-8dd7-4e78177922b9.png">

2022-11-30 15:39 UTC, anithamuthu2022 commented
https://user-images.githubusercontent.com/107003313/204841694-46d94b98-c373-4dc4-8a0b-83fb44bfd8f1.mov

Works perfectly on the landing page and left nav for ENT website.

2022-11-30 15:52 UTC, anithamuthu2022 commented
https://user-images.githubusercontent.com/107003313/204845065-2f14e119-97aa-4f1a-ae90-fbcd28215bbe.mov

Both ENT and OSS works perfectly on the landing page and left nav. 


https://user-images.githubusercontent.com/107003313/204845107-9c4a64a5-4ee9-40d1-8961-a469763996fc.mov

2022-11-30 15:58 UTC, huguestennier commented on docs/themes/v2/layout/home.ejs
> +      <div class="card-light">
```suggestion
      <div class="card card-light">
```

2022-11-30 15:59 UTC, huguestennier commented on docs/themes/v2/layout/home.ejs
> +              <%- partial("component/link", { url: "/app.heartex.com/docs/api", label: "API and SDKs", size: "Full" }) %>
```suggestion
              <%- partial("component/link", { url: "https://app.heartex.com/docs/api", label: "API and SDKs", size: "Full" }) %>
```

2022-11-30 16:00 UTC, anithamuthu2022 commented
@huguestennier @makseq could you review/approve this PR. 

AFAIK, https://heartex.slack.com/archives/C03UN6A0CQN/p1669823891132399?thread_ts=1669652993.899809&cid=C03UN6A0CQN is not including this in PR.

2022-11-30 16:47 UTC, huguestennier approved these changes

2022-11-30 16:56 UTC, merged