feat: Updated_by field on annotation level for "Update", "Accept" and "Reject"
heartexlabs/label-studio pull request #3318
Opened 2022-11-28 19:10 UTC by hakan458

2022-11-30 03:09 UTC, makseq requested changes

2022-11-30 03:09 UTC, makseq commented on label_studio/tasks/migrations/0032_annotation_updated_by_fill.py
> +    Annotation.objects.filter(project=project).update(updated_by=F('completed_by'))
I guess the most correct value for updated by is stored in AnnotationHistory, so probably we can use something like:

```
from annotation_history.models import AnnotationHistory as AH

subquery = AnnotationHistory.objects.filter(annotation_id=OuterRef('pk'), action_type=AH.ActionType.UPDATED).order_by('id')[0])

Annotation.objects
  .filter(project=project).
  .annotate(tmp=subquery)
  .update(updated_by=F('tmp__created_by'))
```
or if postgres doesn't support this, we can rewrite it to simple form with bulk_update.

2022-11-30 03:09 UTC, makseq commented on label_studio/tasks/migrations/0032_annotation_updated_by_fill.py
> +        migration.status = AsyncMigrationStatus.STATUS_FINISHED
this status can't be changed here, it should be done inside of _fill_annotations_updated_by after all calculations

2022-12-02 21:07 UTC, makseq approved these changes

2022-12-02 21:30 UTC, triklozoid approved these changes

2022-12-07 22:05 UTC, merged