fix: DEV-4086: Remove unused indexes
heartexlabs/label-studio pull request #3467
Opened 2022-12-21 11:05 UTC by triklozoid

2023-01-05 22:50 UTC, makseq requested changes

2023-01-05 22:50 UTC, makseq commented on label_studio/tasks/migrations/0035_auto_20221221_1116.py
> +    schema_editor.execute(
it might be a long process, more than 10-20 minutes. Shouldn't we move it to async migration?

2023-01-12 12:13 UTC, triklozoid commented on label_studio/tasks/migrations/0035_auto_20221221_1116.py
> +    schema_editor.execute(
Fixed.

2023-01-13 01:20 UTC, makseq approved these changes

2023-01-13 16:41 UTC, KonstantinKorotaev approved these changes

2023-01-13 16:43 UTC, merged