fix: DEV-4202: Task locks in postponed/skipped queue
heartexlabs/label-studio pull request #3567
Opened 2023-01-17 14:05 UTC by triklozoid

2023-01-18 12:12 UTC, makseq approved these changes

2023-01-20 14:03 UTC, makseq requested changes

2023-01-20 14:03 UTC, makseq commented on label_studio/projects/docs/README.md
> +### Task locks
better to rename to next_task.md

2023-01-20 15:40 UTC, vladimirheartex approved these changes

2023-01-20 17:58 UTC, makseq approved these changes

2023-01-20 17:58 UTC, merged