fix: LSDV-3856: Add get_parent_object mixin
heartexlabs/label-studio pull request #3690
Opened 2023-02-13 16:18 UTC by triklozoid

2023-02-13 19:25 UTC, farioas commented
/git merge develop

2023-02-15 16:06 UTC, makseq requested changes

2023-02-15 16:06 UTC, makseq commented on label_studio/core/utils/common.py
> -    if key not in request.permissions:
https://github.com/heartexlabs/label-studio-enterprise/blob/develop/label_studio_enterprise/activity_log/middleware.py#L162

2023-02-15 16:06 UTC, makseq commented on label_studio/core/utils/common.py
> -    if key not in request.permissions:
we use it in activity logs

2023-02-17 03:10 UTC, makseq approved these changes

2023-02-20 09:38 UTC, MihajloHoma approved these changes

2023-02-20 11:31 UTC, merged