fix: LSDV-4536: Fix numbers ordering in json
heartexlabs/label-studio pull request #3836
Opened 2023-03-14 13:55 UTC by triklozoid

2023-03-22 11:16 UTC, makseq requested changes

2023-03-22 11:16 UTC, makseq commented on label_studio/tests/data_manager/filters/float_tasks.json
> +]
Let add test where data field is dict and list. And user selected number in column type. It should not fail with 500

2023-03-22 17:56 UTC, wesleylima approved these changes

2023-06-21 11:44 UTC, AndrejOros approved these changes

2023-06-22 13:21 UTC, makseq approved these changes

2023-06-22 13:22 UTC, merged