docs: LSDV-4574: Update Audio documentation to point to v3
heartexlabs/label-studio pull request #3842
Opened 2023-03-14 20:42 UTC by bmartel

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [X] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [X] Frontend

### Describe the reason for change
Documentation was not extracting from the correct Audio config comments, and the documentation was out of date as a result.

### Which logical domain(s) does this change affect?
Audio v3 Docs

2023-03-16 01:02 UTC, hlomzik requested changes

2023-03-16 01:02 UTC, hlomzik commented on docs/source/tags/magicwand.md
> +---
We have to wait until [Magic Wand PR](https://github.com/heartexlabs/label-studio/pull/3756) is merged

2023-03-20 14:09 UTC, bmartel commented on docs/source/tags/magicwand.md
> +---
removed from output here so this is not held up in the meantime.

2023-03-20 16:19 UTC, hlomzik approved these changes

2023-03-20 17:33 UTC, merged