fix: LSDV-4700: Add remove_user from org method
heartexlabs/label-studio pull request #3943
Opened 2023-03-31 14:31 UTC by triklozoid

2023-04-04 13:52 UTC, makseq requested changes

2023-04-04 13:52 UTC, makseq commented on label_studio/organizations/models.py
> +        OrganizationMember.objects.filter(user=user, organization=self).delete()
will LseOrganizationMember be removed?

2023-04-04 13:53 UTC, triklozoid commented on label_studio/organizations/models.py
> +        OrganizationMember.objects.filter(user=user, organization=self).delete()
Yes, it's one_to_one with cascade.

2023-04-04 14:02 UTC, makseq approved these changes

2023-04-05 15:46 UTC, vladimirheartex approved these changes

2023-04-11 15:17 UTC, merged