chore: LSDV-5060: Migrate to Yarn
heartexlabs/label-studio pull request #4160
Opened 2023-05-09 16:41 UTC by robot-ci-heartex

Hi @nicholasrq!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/dm2/pull/182

2023-05-10 14:11 UTC, hlomzik requested changes

2023-05-10 14:11 UTC, hlomzik commented on .github/workflows/follow-merge-upstream-repo-sync.yml
> +        run: npm install -g jsdoc-to-markdown node-fetch
These modules are installed for main LSF code, so they should be accessible already. Try to remove this step completely and check Docs Build

2023-05-11 15:28 UTC, nicholasrq approved these changes

2023-05-11 15:32 UTC, hlomzik approved these changes

2023-05-11 17:29 UTC, merged