fix: LSDV-E-135: Dependabot updates
heartexlabs/label-studio pull request #4324
Opened 2023-06-05 21:01 UTC by robot-ci-heartex

Hi @Travis1282!

This PR was created in response to a PRs in upstream repo:
- https://github.com/heartexlabs/dm2/pull/204

2023-06-06 16:39 UTC, hlomzik submitted a review, later dismissed

2023-06-06 16:39 UTC, hlomzik commented on docs/source/guide/storage.md
> +- If you're syncing image or audio files, make sure **Treat every bucket object as a source file** is enabled.
duplication after merge I guess

2023-06-06 16:39 UTC, hlomzik commented on docs/source/templates/intent_classification.md
> +<!-- md nested-classification.md -->
another duplication

2023-06-06 16:39 UTC, hlomzik commented on scripts/serve_local_files.sh
> +cd "$INPUT_DIR"
is it intented fix?

2023-06-06 23:09 UTC, bmartel approved these changes

2023-06-07 13:11 UTC, hlomzik requested changes

2023-06-07 13:11 UTC, hlomzik commented on label_studio/frontend/dist/dm/version.json
> +<<<<<<< HEAD
so now it's even worse =(

2023-06-07 14:00 UTC, hlomzik requested changes

2023-06-07 14:00 UTC, hlomzik commented on label_studio/core/static/js/478.chunk.js.map
that one is mistakenly added too I guess

2023-06-07 15:39 UTC, hlomzik requested changes
These sourcemaps are better to be reverted as well, don't think they should be changed

2023-06-07 16:47 UTC, closed without merging