Release 0.8.1
heartexlabs/label-studio pull request #472
Opened 2020-10-27 18:40 UTC by makseq

2020-10-29 14:19 UTC, kasuteru requested changes
Hi, I tested this and it works. However, i would propose making the following changes in line 37 / 77 to add a tooltip with the full path on hover:

    <i class="word-break" v-if="project.multi_session_mode" v-b-tooltip.hover :title="project.source_storage.readable_path">{{

for source storge, same for target storage.

Let me know whether you want to change it or whether I should send you a PR with the new version.

2020-10-29 19:45 UTC, makseq commented
@kasuteru 
> Hi, I tested this and it works. However, i would propose making the following changes in line 37 / 77 to add a tooltip with the full path on hover:
> 
> ```
> <i class="word-break" v-if="project.multi_session_mode" v-b-tooltip.hover :title="project.source_storage.readable_path">{{
> ```
> 
> for source storge, same for target storage.
> 
> Let me know whether you want to change it or whether I should send you a PR with the new version.

Done!

2020-11-02 10:18 UTC, kasuteru approved these changes
Tested in Ubuntu VM and with Firefox & Chrome on Windows, works as expected.

2020-11-20 05:09 UTC, niklub approved these changes

2020-11-20 05:10 UTC, merged