doc: DOC-196: Reorganize the Labeling section in the docs
heartexlabs/label-studio pull request #5527
Opened 2024-03-04 00:37 UTC by caitlinwheeless

As part of doc reorg work, created a new "Administration" section 

Community:
- Added new page labeling config tags and parameters
- Broke labeling page into:
- Labeling (rewrote)
    - New page on labeling panes
   - New page on hotkeys and settings (rewrote)
    - New page on advanced labeling (rewrote)

Enterprise:
- All the changes in Community
- Moved Comments and Notifications page to the "Quality Control" section

This PR affects:

- [X] Community docs
- [X] Enterprise docs

2024-03-04 00:39 UTC, caitlinwheeless commented
Unintentionally brought in the commit history for a previous branch  😐

2024-04-10 02:40 UTC, makseq requested changes
Please check all png files, most of them have a pretty big size (more 400 Kb), I believe they can have ~100 Kb if you use JPG or if you try to use some sort of compression for PNG.

2024-04-10 02:40 UTC, makseq commented on docs/source/guide/hotkeys.md
> +* **Labeling hotkeys**--Enables hotkeys for labels and choices.
```suggestion
* **Labeling hotkeys** -- Enables hotkeys for labels and choices. 
```

2024-04-10 02:40 UTC, makseq commented on docs/source/guide/hotkeys.md
> +* **Show hotkeys on labels**--If hotkeys for labels and choices are enabled, this will display the hotkey value next to the option.
```suggestion
* **Show hotkeys on labels** -- If hotkeys for labels and choices are enabled, this will display the hotkey value next to the option.
```

2024-04-10 02:40 UTC, makseq commented on docs/themes/v2/source/images/label/stream_view.png
This image size is huge.. probably it's better to use JPG or some compression for PNG

2024-04-10 02:40 UTC, makseq commented on docs/themes/v2/source/images/label/visual_editor.gif
This gif is too large, there are some compression services available on the internet, pls try to use them

2024-04-10 02:40 UTC, makseq commented on docs/themes/v2/source/images/label/regions_panel.gif
I believe this gif can be compressed to have ~300-400 Kb without losing quality too much

2024-04-10 03:40 UTC, makseq requested changes

2024-04-10 03:40 UTC, makseq commented on docs/source/guide/label_object.md
> +- Using “url”: `<Text name="text1" value="$text" valueType="url"/>` displays the text loaded by the URL.
```suggestion
- Using “url”: `<Text name="text1" value="$text_url" valueType="url"/>` displays the text loaded by the URL. The task data should contain URL and might look like this: 
    ```
    {"text_url": "http://example.com"}
    ```
```

2024-04-10 03:40 UTC, makseq commented on docs/source/guide/label_object.md
> +- Using “url”: `<Text name="text1" value="$text" valueType="url"/>` displays the text loaded by the URL.
Please check how it looks in the rendered documentation!

2024-04-10 03:40 UTC, makseq commented on docs/source/guide/label_object.md
> +- Using “text”: `<Text name="text" value="$text" valueType="text"/>` displays the URL without loading the text.
```suggestion
- Using “text”: `<Text name="text" value="$text" valueType="text"/>` displays the URL without loading the text. The task data should contain plain text and might look like this: 
    ```
    {"text": "this is a plain text to display"}
    ```

```

2024-04-10 03:40 UTC, makseq commented on docs/source/guide/label_object.md
> +- Using “text”: `<Text name="text" value="$text" valueType="text"/>` displays the URL without loading the text.
Please check how it looks in the rendered documentation!

2024-04-15 17:50 UTC, makseq requested changes
![image](https://github.com/HumanSignal/label-studio/assets/501780/a0d58871-f519-40a4-9210-adfec6bd806c)

I would place Label Regions after Labeling interface

2024-04-16 02:39 UTC, makseq requested changes

2024-04-16 02:39 UTC, makseq commented on docs/source/guide/label_advanced.md
> +## Faster image labeling
Can we add a short video (gif?) to show how it works

2024-04-16 02:39 UTC, makseq commented on docs/source/guide/label_advanced.md
> +5. Select the label that you want to apply to the region.
this sounds weird - we are trying to create regions without labels and here we suggest to select a label

2024-04-16 02:39 UTC, makseq commented on docs/source/guide/label_object.md
> +title: Retrieve imported data in the labeling configuration
This title is bad.. Actually we have this section - https://deploy-preview-5527--label-studio-docs-new-theme.netlify.app/guide/label_components#Variables - and it's very related to this whole page. 

This title should be like "Variable values and types"

2024-04-16 02:43 UTC, makseq requested changes

2024-04-16 02:43 UTC, makseq commented on docs/source/guide/label_object.md
> +title: Retrieve imported data in the labeling configuration
The long title can be "Retrieve imported data in the labeling configuration" => "Variable values and value types: different ways of data loading in the labeling configuration"

2024-04-16 13:49 UTC, makseq requested changes

2024-04-16 13:49 UTC, makseq commented on docs/source/guide/label_object.md
> +---
Is this page new? label_object.md? If yes, let's rename it to label_values.md or label_variables.md

2024-04-16 13:49 UTC, makseq commented on docs/source/guide/label_object.md
> +In order to get data into tasks, you have to [import it](tasks). Then you have to specify how you want to retrieve that data to use it in a task. This is done with object tags.
This section and text are very blurry. Let's rewrite it to something like this: 

```suggestion
All object tags are intended to load and display data into the labeling interface. The each object tag has the `value` field and it should point to a `task['data']` dictionary field.
```

2024-04-16 13:49 UTC, makseq commented on docs/source/guide/label_object.md
> +In order to get data into tasks, you have to [import it](tasks). Then you have to specify how you want to retrieve that data to use it in a task. This is done with object tags.
Then we need to cut the whole Variables section from this page and move it here:
![image](https://github.com/HumanSignal/label-studio/assets/501780/393d8646-1866-472c-a11b-e9a21a1fcc94)

In the original page we should keep Variables section, but make a link to this page.

2024-04-16 13:49 UTC, makseq commented on docs/source/guide/label_components.md
> +title: Use tags and parameters when customizing the labeling interface
maybe "Tags and parameters for customizing the labeling interface

2024-04-16 19:08 UTC, makseq requested changes

2024-04-16 19:08 UTC, makseq commented on docs/source/guide/label_components.md
> +## Variables
```suggestion
## Variables

Variables are presented as `value` in object tags. See more details: <here is the link to the new 'Variable values and value types' (in your version it's named as 'Retrieve data....') page>

other text should be moved to the new page.
```

2024-06-21 01:48 UTC, closed without merging