fix: HUMSIG-37: Visual fixes
heartexlabs/label-studio pull request #5660
Opened 2024-04-03 05:02 UTC by makseq

### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2024-04-03 14:20 UTC, makseq commented
/git merge develop

2024-04-03 14:22 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/AnnotationSettings/ModelVersionSelector.js
> +          Select which predictions or which model you want to use:
wrong indent
```suggestion
        Select which predictions or which model you want to use:
```

2024-04-03 14:23 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningList.js
> +import {Tooltip} from "../../../components/Tooltip/Tooltip";
```suggestion
import { Tooltip } from "../../../components/Tooltip/Tooltip";
```

2024-04-03 14:30 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/MachineLearningSettings/MachineLearningSettings.js
> +          <Description style={{ marginTop: 0, maxWidth: 680, lineHeight:'1.5em' }}>
```suggestion
          <Description style={{ marginTop: 0, maxWidth: 680, lineHeight: "1.5em" }}>
```

2024-04-03 14:32 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/PredictionsSettings/PredictionsSettings.js
> +            <Description  style={{ marginTop: 14 }}>
move this to styles file

2024-04-03 14:32 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/PredictionsSettings/PredictionsSettings.js
>              <Elem name={'title'}>Predictions List</Elem>
```suggestion
          <Elem name="title-block">
            <Elem name="title">Predictions List</Elem>
```

2024-04-03 14:32 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/PredictionsSettings/PredictionsSettings.js
> +            <Description  style={{ marginTop: 14 }}>
and why do you description inside `title-block`?

2024-04-03 14:33 UTC, hlomzik requested changes
minor comments

2024-04-03 15:31 UTC, hlomzik commented on web/apps/labelstudio/src/pages/Settings/PredictionsSettings/PredictionsSettings.js
> +            <Description  style={{ marginTop: 14 }}>
ah, that's external component, then this style is good.
but title-block > description is still a little confusing

2024-04-04 12:32 UTC, makseq commented
/git merge develop

2024-04-04 16:32 UTC, makseq commented
/git merge develop

2024-04-04 17:26 UTC, hlomzik approved these changes

2024-04-04 17:35 UTC, merged