feat: jsonL suppo
heartexlabs/label-studio pull request #5830
Opened 2024-05-06 16:39 UTC by Jorjeous

### PR fulfills these requirements
- [+] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [-] Tests for the changes have been added/updated (for bug fixes/features)
- [-] Docs have been added/updated (for bug fixes/features)
- [-] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [+] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend
- [+] OtherBackend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_
People often confuse json and jsonL
The nemo framework deliberately uses the name json, although in fact it is jsonL

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_
Ability to import jsonL

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_
No 

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_
No

#### Does this change affect security?
_(if so describe the impacts positive or negative)_
No

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [+] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit
- [+] Manual

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_
Data import

2024-05-08 19:22 UTC, sajarin commented
/jira create

2024-06-04 16:29 UTC, Jorjeous commented
After that pr I'm going to add 
1) some new default templates
2) scripts for cutting long audios to small jobs using NFA (Nemo Forced Aligner) 
3) template for long audio, that utilizes ML backend, and java script, that follows text (according to the audio)

2024-06-10 19:41 UTC, sajarin commented
thanks for the PR @Jorjeous, our team is working through some PRs and we'll have a review for this one soon, thanks for being patient! 

related reports for jsonL support: 
https://github.com/HumanSignal/label-studio-converter/issues/58
https://github.com/HumanSignal/label-studio/issues/1960
https://github.com/HumanSignal/label-studio/issues/4607

2024-06-10 20:58 UTC, makseq requested changes

2024-06-10 20:58 UTC, makseq commented on label_studio/data_import/models.py
> +            if 'audio_filepath' in task_data:
what is it? It shouldn't be depended on any specific keys in task.data

2024-06-10 20:58 UTC, makseq commented on label_studio/data_import/models.py
> +                            audio_upload = create_file_upload(self.user, self.project, SimpleUploadedFile(os.path.basename(audio_path), audio_file.read()))
It most cases LS doesn't have an access to audio_path, because it's deployed on a separated machine/docker

2024-08-13 01:53 UTC, closed without merging