Release 0.9.1.post2
heartexlabs/label-studio pull request #610
Opened 2021-02-19 18:08 UTC by makseq

2021-02-26 10:14 UTC, DominikZians approved these changes
This should improve compatibility with other libraries, notably spaCy which uses a higher version of wasabi

2021-02-26 10:16 UTC, DominikZians approved these changes

2021-03-10 12:32 UTC, Khemist-sis requested changes
I

2021-03-10 12:48 UTC, makseq commented
@Khemist-sis Sorry, but what did you mean ?

2021-03-26 14:00 UTC, closed without merging