feat: add region:visibility-all shortcut (ctrl+h)
heartexlabs/label-studio pull request #6212
Opened 2024-08-15 14:57 UTC by LouisJULIEN

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [X] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_
No shortcut existed to hide all regions. It had to be done through a click tot he dedicated button on the sidebar

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_
by default, ctrl+h now hide all regions if one is visible. If none is visible, it show all regions.

#### What is the current behavior?
_(if this is a breaking or feature change)_
ctrl + h has no behavior on label studio.

#### What libraries were added/updated?
_(list all with version changes)_
None

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_
No

#### Does this change affect security?
_(if so describe the impacts positive or negative)_
No

#### What alternative approaches were there?
_(briefly list any if applicable)_
Click on the sidebar button

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_
None

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit
Does manual testing counts for a shortcut (I kind of hate myself for asking)?

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2024-08-19 13:23 UTC, LouisJULIEN commented
I reverted my changes made to web/dist, no idea if that's what's expected

2024-09-02 14:47 UTC, LouisJULIEN commented
Hello! Would it be possible to review this PR? I tried to make it as small and as little as possible to ease review. Thanks!

2024-09-06 10:49 UTC, LouisJULIEN commented
Up! @hlomzik maybe?

2024-09-23 12:03 UTC, LouisJULIEN commented
Up!  I'm trying with @yyassi-heartex this time

2024-09-23 13:21 UTC, hlomzik commented
/jira create

2024-09-23 13:25 UTC, hlomzik commented
Oh, thank you for patience and for this contribution, @LouisJULIEN !
It's very straightforward and precise improvement, we'll run it through our process and will merge soon!

2024-09-27 14:40 UTC, LouisJULIEN commented
Hey @hlomzik , thanks for running the CI. Is everything good?

2024-10-01 12:04 UTC, LouisJULIEN commented
up @hlomzik

2024-10-02 14:44 UTC, hlomzik requested changes

2024-10-02 14:44 UTC, hlomzik commented on web/libs/editor/src/core/settings/keymap.json
> +    "mac": "command+h",
```suggestion
    "mac": "ctrl+h",
```
`⌘+H` is a Mac global hotkey to hide a window, so let's use `ctrl+h` on every platform and explicitly state this in here.

2024-10-04 14:48 UTC, LouisJULIEN commented on web/libs/editor/src/core/settings/keymap.json
> +    "mac": "command+h",
good catch

2024-10-04 16:21 UTC, makseq commented
/git merge develop

2024-10-08 00:23 UTC, hlomzik approved these changes

2024-10-08 13:16 UTC, bmartel approved these changes

2024-10-08 13:17 UTC, bmartel commented
/git merge develop

2024-10-10 14:02 UTC, merged