fix: OPTIC-987: convert styl to scss
heartexlabs/label-studio pull request #6228
Opened 2024-08-20 16:45 UTC by carly-bartel

convert styl to scss in LS web/libs/editor/src/components/

2024-08-20 19:39 UTC, yyassi-heartex commented on web/libs/editor/src/components/AnnotationTabs/AnnotationTabs.scss
> +.annotation-tabs {
web/libs/editor/src/components/AnnotationTabs/AnnotationTabs.styl doesnt appear to have been removed

2024-08-20 21:09 UTC, yyassi-heartex commented
/git merge develop

2024-08-20 21:54 UTC, bmartel commented on web/libs/editor/src/components/AnnotationsCarousel/AnnotationsCarousel.scss
> +    transform: translateX(calc(-1 * var(0px)));
```suggestion
    transform: translateX(calc(-1 * var(--carousel-left)));
```

2024-08-20 22:37 UTC, yyassi-heartex approved these changes

2024-08-21 14:04 UTC, bmartel commented on web/libs/editor/src/components/Entities/RegionItem.scss
I believe there is a missing deletion of the corresponding stylus file `web/libs/editor/src/components/Entities/RegionItem.styl`

2024-08-21 14:08 UTC, bmartel requested changes
There appears to be a couple stylus files remaining to be removed

<img width="1496" alt="Screenshot 2024-08-21 at 9 06 48 AM" src="https://github.com/user-attachments/assets/7453591a-d12b-413e-a895-32e43715763d">

2024-08-21 14:16 UTC, bmartel approved these changes
Approving based on the removals of the 2 leftover stylus files in the editor components.

2024-08-22 16:34 UTC, yyassi-heartex commented
/git merge develop

2024-08-23 13:46 UTC, MihajloHoma approved these changes

2024-08-23 17:04 UTC, yyassi-heartex commented
/git merge develop

2024-08-23 17:11 UTC, yyassi-heartex commented
/git merge develop

2024-08-23 17:52 UTC, yyassi-heartex commented
/git merge develop

2024-08-23 19:46 UTC, yyassi-heartex commented
/git merge develop

2024-08-23 20:53 UTC, merged