docs: DOC-264: Add export options to video object tracking template
heartexlabs/label-studio pull request #6620
Opened 2024-11-08 18:36 UTC by caitlinwheeless

Add steps for exporting with interpolated frames

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Enterprise docs
- [ ] Community docs

2024-11-08 20:03 UTC, makseq requested changes

2024-11-08 20:03 UTC, makseq commented on docs/source/templates/video_object_detector.md
> +  "video": "/static/samples/opossum_snow.mp4"
it's better to keep this link, it works everywhere: 
```suggestion
  "video": "https://htx-pub.s3.amazonaws.com/samples/opossum_snow.mp4"
```

2024-11-08 20:03 UTC, makseq commented on docs/source/templates/video_object_detector.md
> +
seems we don't need this section, because it repeats the same as it was in #### Use the API to create an export snapshot with interpolation enabled

2024-11-08 20:12 UTC, caitlinwheeless commented on docs/source/templates/video_object_detector.md
> +
Removed

2024-11-11 12:00 UTC, hlomzik approved these changes

2024-11-19 21:10 UTC, makseq approved these changes

2024-11-19 21:11 UTC, merged