chore: bump label studio sdk to released version
heartexlabs/label-studio pull request #6752
Opened 2024-12-03 22:35 UTC by jombooth

need a released version of LS sdk for pypi upload

2024-12-03 22:44 UTC, wesleylima approved these changes

2024-12-04 18:26 UTC, farioas commented
/git merge develop

2024-12-04 18:59 UTC, nikitabelonogov requested changes
This will brake Follow Merge for SDK->LS
please update it only in release branch

2024-12-04 18:59 UTC, nikitabelonogov requested changes
@jombooth This will brake Follow Merge for SDK->LS
please update it only in release branch

2024-12-06 10:11 UTC, closed without merging