fix: OPTIC-1420: Inner IDs are duplicated and counted wrong
heartexlabs/label-studio pull request #6785
Opened 2024-12-12 14:25 UTC by mcanu

### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Backend (Database)
- [ ] Backend (API)
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2024-12-16 17:55 UTC, mcanu commented
/git merge develop

2024-12-18 15:54 UTC, mcanu commented
/git merge develop

2024-12-18 16:21 UTC, makseq requested changes

2024-12-18 16:21 UTC, makseq commented on label_studio/tasks/serializers.py
> +        last_task = Task.objects.filter(project=project).order_by('-inner_id').first()
use fast_first instead, first() might be very slow

2024-12-18 16:21 UTC, makseq commented on label_studio/tasks/serializers.py
> +        last_task = Task.objects.filter(project=project).order_by('-inner_id').first()
or use [0] as it was before

2024-12-18 17:52 UTC, wesleylima approved these changes

2024-12-18 18:53 UTC, makseq approved these changes

2024-12-18 18:54 UTC, merged