Enable Local Export storage storage
heartexlabs/label-studio pull request #776
Opened 2021-04-08 16:01 UTC by Edern76

This PR aims to enable the use of a local folder of the server as a local storage by allowing the API to access the classes required to do so, with some slight corrections.

2021-04-13 10:03 UTC, niklub requested changes
Thanks a lot for your contribution! Really appreciate it. Just a few minor things to check

2021-04-13 15:35 UTC, Edern76 commented on label_studio/io_storages/localfiles/serializers.py
> +            storage.validate_connection()
Didn't realize initially the base class' validate_connection method was a simple pass, thanks for pointing this out, I removed that part in the latest commit

2021-04-13 15:37 UTC, Edern76 commented on label_studio/io_storages/localfiles/models.py
> +
Thanks for pointing this out, should be now fixed :)

2021-04-13 18:24 UTC, niklub approved these changes

2021-04-16 07:44 UTC, triklozoid approved these changes

2021-04-16 08:34 UTC, merged